### ISSUE TITLE
Add unit test for Drupal extension detection

### ISSUE THREAD

**Issue by SniperSister** [CMS-Garden/cmsscanner#13]

**Comment by SniperSister** [comment]
@tobiasbaehr any help here would be very appreciated! :)

**Comment by tobiasbaehr** [comment]
I added testModulesAreDetected.

**Comment by zero-24** [comment]
Closing as there is now the unittest. Thanks @tobiasbaehr

**Comment by SniperSister** [comment]
Awesome, thanks from my side too!
