### ISSUE TITLE
Enhance the readme.md with information about tests

### ISSUE THREAD

**Issue by robinboening** [CMS-Garden/cmsscanner#37]
As a developer I want to be able to know what prerequisites are needed to run the tests and how do I run the tests.

This is a very nice template for a fully comprehensive `README.md`: https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

For this issue I only point on the tests in particular: https://gist.github.com/PurpleBooth/109311bb0361f32d87a2#running-the-tests

**Comment by zero-24** [comment]
Closing please review and comment on #51 thanks @robinboening
