### ISSUE TITLE
Create cmsscanner.phar tutorial

### ISSUE THREAD

**Issue by zero-24** [CMS-Garden/cmsscanner#43]
@degobbis did a step by step example where how to do the cmsscanner.phar in german. Where do you want to have that? A wiki entry here on github or better in the readme?

**Comment by SniperSister** [comment]
Put it in the wiki :)

**Comment by zero-24** [comment]
Done: https://github.com/CMS-Garden/cmsscanner/wiki/Create-cmsscanner.phar-tutorial + https://github.com/CMS-Garden/cmsscanner/wiki
