### ISSUE TITLE
Merging feature/whd-hackathon?

### ISSUE THREAD

**Issue by helmo** [CMS-Garden/cmsscanner#44]
Hi,

Do you have a timeline when you would like to have the feature/whd-hackathon branch merged?
Or is there is list blockers?
I don't mind rebasing my feature branches again, but would like to get these finished.

**Comment by SniperSister** [comment]
Hi,

I'm so sorry for the delay, I'm very busy with an other CMS-Garden project right now and didn't had time to fix the last blocker yet:
https://github.com/CMS-Garden/cmsscanner/pull/41

This also solves the "missing" extension detection support in your PR, so they are closely connected.

I reserved some time during the next 3 weeks to get this finally done!

Cheers,
David

**Comment by SniperSister** [comment]
WHD branch is merged to dev :)
