### ISSUE TITLE
phpBB detected as Contendio

### ISSUE THREAD

**Issue by helmo** [CMS-Garden/cmsscanner#49]
Hi,

A site with [phpBB 3](https://www.phpbb.com/) gets detected as Contendio based on a file called startup.php.
I think the detectSystem method needs to be a bit more specific.

**Comment by SniperSister** [comment]
The proper place for this would be https://github.com/CMS-Garden/cmsscanner/blob/develop/src/Detector/Adapter/ContenidoAdapter.php#L110, right?

**Comment by helmo** [comment]
yes

**Comment by SniperSister** [comment]
@clausissimo can I please ask you to fix this?

**Comment by SniperSister** [comment]
Fixed it myself :) @helmo can you please check the PR referenced above?

**Comment by zero-24** [comment]
Closing as the PR is merged now. Thanks
