### ISSUE TITLE
Arch linux package

### ISSUE THREAD

**Issue by sanduhrs** [CMS-Garden/cmsscanner#53]
FYI: I did package cmsscanner for Arch linux: https://aur.archlinux.org/packages/cmsscanner/

**Comment by SniperSister** [comment]
Oh nice 👍  Thank you, I really appreciate the contribution!

**Comment by zero-24** [comment]
Here is a PR to add that to the readme see: #54

**Comment by zero-24** [comment]
Closing as the PR got merged thanks @sanduhrs 👍
