### ISSUE TITLE
Joomla - Exclude Core Extensions

### ISSUE THREAD

**Issue by hamby** [CMS-Garden/cmsscanner#9]
To improve the performance of the CMSScanner is attached an exclude list for core stuff. The Core extensions normally will be updated with the core update, therefore its reasonable do not search this directories for xml files. One more advantage is the clean output. Through the filter you getting only result of external extensions.

- Components 
- Plugins
- Modules
- Manifests

Lets start a discussion. Whats your meaning about this?

[J1.0.X_blacklist.txt](https://github.com/CMS-Garden/cmsscanner/files/172161/J1.0.X_blacklist.txt)
[J1.5.X_blacklist.txt](https://github.com/CMS-Garden/cmsscanner/files/172165/J1.5.X_blacklist.txt)
[J1.6.X_blacklist.txt](https://github.com/CMS-Garden/cmsscanner/files/172162/J1.6.X_blacklist.txt)
[J1.7.X_blacklist.txt](https://github.com/CMS-Garden/cmsscanner/files/172163/J1.7.X_blacklist.txt)
[J2.5.X_blacklist.txt](https://github.com/CMS-Garden/cmsscanner/files/172164/J2.5.X_blacklist.txt)
[J3.0.X-J3.4.X_blacklist.txt](https://github.com/CMS-Garden/cmsscanner/files/172166/J3.0.X-J3.4.X_blacklist.txt)

**Comment by SniperSister** [comment]
I personally wouldn't fix this. It's a lot of stuff to implement, it requires a lot of effort to maintain it and as extensions are only outputted in the JSON file anyway, core extensions can be filtered easily.
